# Generated by Django 5.2.4 on 2026-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='alert_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
    ]
