# Generated by Django 5.2.4 on 2026-01-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_vitalsign_alert_message_vitalsign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='critical', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patient')),
                ('vital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.vitalsign')),
            ],
        ),
    ]
