# Generated by Django 5.2.4 on 2026-01-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_vitalalertlog_options_consultationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.vitalalert'),
        ),
    ]
