# Generated by Django 5.2.4 on 2026-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_vitalalert_acknowledged_at_vitalalert_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalalert',
            name='escalated_to',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('head_doctor', 'Head Doctor'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
