# Generated by Django 5.2.4 on 2026-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_vitalalert_escalated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='sla_admin_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sla_doctor_ack_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sla_head_doctor_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
