# Generated by Django 5.2.4 on 2026-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_hospital_sla_admin_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
