# Generated by Django 5.2.4 on 2026-01-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_customuser_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal')], max_length=10)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Time allowed before alert must be acknowledged')),
                ('escalation_time_minutes', models.PositiveIntegerField(help_text='Time after which alert escalates')),
                ('max_escalation_level', models.PositiveIntegerField(default=3, help_text='Doctor → Head Doctor → Admin')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='billing.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'severity')},
            },
        ),
    ]
