# Generated by Django 5.2.4 on 2026-01-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_slapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalalert',
            name='acknowledge_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalalert',
            name='escalation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalalert',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalalert',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.slapolicy'),
        ),
        migrations.AlterField(
            model_name='vitalalert',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
