# Generated by Django 5.2.4 on 2026-01-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_vitalalert_acknowledge_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='third_party_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='third_party_type',
            field=models.CharField(choices=[('none', 'None'), ('nhis', 'NHIS / Government'), ('sponsor', 'Hospital Sponsored')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('self', 'Self Pay'), ('nhis', 'NHIS / Government'), ('free', 'Hospital Sponsored')], max_length=20)),
                ('patient_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('government_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.patient')),
            ],
        ),
    ]
