# Generated by Django 5.2.4 on 2026-01-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_bill_is_fully_paid_bill_patient_payable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('payer_type', models.CharField(choices=[('federal', 'Federal (NHIS)'), ('state', 'State Scheme'), ('private', 'Private Sponsor'), ('hospital', 'Hospital Sponsored')], max_length=20)),
                ('default_patient_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_payer_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='patientcoverage',
            old_name='government_percentage',
            new_name='payer_percentage',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='third_party_type',
        ),
        migrations.RemoveField(
            model_name='patientcoverage',
            name='coverage_type',
        ),
        migrations.AddField(
            model_name='bill',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.thirdpartypayer'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.thirdpartypayer'),
        ),
    ]
