# Generated by Django 5.2.4 on 2026-01-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_thirdpartypayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='claim_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='claim_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
