# Generated by Django 5.2.4 on 2026-02-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_bill_claim_reference_bill_claim_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('payer_type', models.CharField(choices=[('nhis', 'NHIS (Federal)'), ('state', 'State Health Insurance'), ('hospital', 'Hospital Sponsored')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientcoverage',
            name='patient_percentage',
        ),
        migrations.RemoveField(
            model_name='patientcoverage',
            name='payer_percentage',
        ),
        migrations.AlterField(
            model_name='patientcoverage',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.payer'),
        ),
    ]
