# Generated by Django 5.2.4 on 2026-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_payer_remove_patientcoverage_patient_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcoverage',
            name='government_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='patient_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
