# Generated by Django 5.2.4 on 2026-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_patientcoverage_government_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcoverage',
            name='government_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patientcoverage',
            name='patient_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payer',
            name='payer_type',
            field=models.CharField(choices=[('government', 'Government'), ('state', 'State Government'), ('hospital', 'Hospital'), ('private', 'Private')], max_length=20),
        ),
    ]
