# Generated by Django 5.2.4 on 2026-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_patientcoverage_government_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Hospital Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('lab', 'Lab Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant')], default='receptionist', max_length=20),
        ),
    ]
