# Generated by Django 5.2.4 on 2026-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_logos/'),
        ),
    ]
