# Generated by Django 4.2.7 on 2026-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_customuser_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Hospital Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('lab', 'Lab Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant')], default='receptionist', max_length=20),
        ),
    ]
