# Generated by Django 4.2.7 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
