# Generated by Django 4.2.7 on 2026-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_appointment_is_walk_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
