# Generated by Django 4.2.7 on 2026-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_patientvisit_is_active_patientvisit_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.patientvisit'),
        ),
    ]
