# Generated by Django 4.2.7 on 2026-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_medicalrecord_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to='radiology_scans/'),
        ),
    ]
