# Generated by Django 5.2.4 on 2026-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_radiologyrequest_scan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
