# Generated by Django 5.2.4 on 2026-04-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_patientvisit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'accountant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('front_desk', 'Front Desk'), ('pharmacy', 'Pharmacy')], default='front_desk', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.medicine'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.service'),
        ),
    ]
