# Generated by Codex to fix missing column in production DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0032_create_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]

