# Generated by Django 5.2.4 on 2026-05-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('billing', '0034_hospital_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('admin', 'Hospital Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant')], default='receptionist', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['hospital'], name='billing_cus_hospita_d8fa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='billing_cus_role_eb84a8_idx'),
        ),
    ]
