# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0035_alter_customuser_options_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
    ]

