# Generated by Django 4.2.7 on 2026-09-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_hospital_phone_number'),
        ('billing', '0036_subscription_is_trial'),
    ]

    operations = [
    ]
